### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by andrewheartsxd** [jasonmit/virtual-each#40] opened 2016-05-12 20:37 UTC
I was able to get this working and it's pretty good but there is some lag in scrolling. My use case involves one level of nested components inside the #virtual-each which I thought might be a problem, but for the gif below I took it out and it it still lags:

    {{#virtual-each alphabetizedArchetypes height=height itemHeight=itemHeight scrollTimeout=0 as |archetype|}}
      <li class="list-group-item asset-list-item">
         <div class="asset-list-item-text">{{archetype.name}}</div>
      </li>
    {{/virtual-each}}

![virtual-each-scrolling](https://cloud.githubusercontent.com/assets/8338394/15229603/9f493564-1846-11e6-9af4-a993ae4f2be7.gif)

I was wondering if there's anything I can do to get it as fast as the example.

**Comment by jasonmit** [comment] 2016-05-12 21:45
Can you push an example that replicates this behavior so I can see what may be going on.

**Comment by jasonmit** [comment] 2016-05-26 21:19
Closing since reporter never came back with steps to reproduce.

**Closed by jasonmit** 2016-05-26 21:19 UTC
Labels: question
